on:
  # Trigger analysis when creating a pull request.
  workflow_dispatch:
  pull_request:
      branches: [master]
      types: [opened, synchronize, reopened]
      
concurrency:
  group: SonarQube
  
name: Code Analysis
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarQube Scan  
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
